import {  Inter } from 'next/font/google'
import './globals.css'
import "../public/home.css" 

const inter = Inter({ subsets: ['latin'], weight: '500' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, admin, analytics, dashboard, team }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <div className='routing'>
        {admin}
        {analytics}
        {dashboard}
        {team}
        </div>
        </body>
    </html>
  )
}
